apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pelican-wings
  namespace: pelican
  labels:
    app.kubernetes.io/managed-by: pelican-wings
    app.kubernetes.io/component: wings
subjects:
  - kind: ServiceAccount
    name: pelican-wings
    namespace: pelican
roleRef:
  kind: Role
  name: pelican-wings
  apiGroup: rbac.authorization.k8s.io
