{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pelican-wings.fullname" . }}-metrics
  labels:
    {{- include "pelican-wings.labels" . | nindent 4 }}
rules:
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
  # Proxy to kubelet stats/summary API for resource metrics when
  # metrics-server is not installed.
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
{{- end }}
